export const MARKETPLACE = process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS;
export const NFT_TOKEN = process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS;
export const IPFS_DEDICATED_NODE = process.env.NEXT_PUBLIC_IPFS_DEDICATED_NODE;
export const INFURA_PROJECT_ID = process.env.NEXT_PUBLIC_INFURA_PROJECT_ID;
export const INFURA_SECRET_API = process.env.NEXT_PUBLIC_INFURA_SECRET_API;
export const PINATA_API_SECRET = process.env.NEXT_PUBLIC_PINATA_API_SECRET;
export const PINATA_API_KEY = process.env.NEXT_PUBLIC_PINATA_API_KEY;