export const MARKETPLACE = process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS;
export const NFT_TOKEN = process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS;
export const IPFS_DEDICATED_NODE = process.env.NEXT_PUBLIC_IPFS_DEDICATED_NODE;